### ISSUE TITLE
Incorrect Output, Zero in first cell. 

### ISSUE THREAD

**Issue by DRAGONFALCON** [PerrierRemi/warframe_market_price_obtention#4]
data.csv was created exactly as the example in the Colab description. 

item,component,number
Akbolto,Link
Aklex,Blueprint
Aklex,Link
Frost,Systems

However, the output for the price.csv is just a 0 in the first cell. No prices or anything else were outputted. 

Of course I may be doing something wrong, not sure what. 

Let me know how I can improve this bug report.

**Comment by PerrierRemi** [comment]
It was a issue in main, using tqdm in a list comprehension expression was returning nothing.
